import ProductOne from './assets/product1.jpg'
import ProductTwo from './assets/product2.jpg'
import ProductThree from './assets/product3.png'

let data = [
    {
        id: "01",
        title: "Product One",
        price: "30$",
        image: ProductOne,
    },
     {
        id: "02",
        title: "Product Two",
        price: "70$",
        image: ProductTwo,
    },
     {
        id: "03",
        title: "Product Three",
        price: "40$",
        image: ProductThree,
    },
    {
        id: "04",
        title: "Product Four",
        price: "50$",
        image: ProductOne,
    },
     {
        id: "05",
        title: "Product Five",
        price: "40$",
        image: ProductTwo,
    },
     {
        id: "06",
        title: "Product Six",
        price: "550$",
        image: ProductThree,
    },
     {
        id: "07",
        title: "Product Seven",
        price: "110$",
        image: ProductOne,
    },
     {
        id: "08",
        title: "Product Eight",
        price: "140$",
        image: ProductTwo,
    },
     {
        id: "09",
        title: "Product Nine",
        price: "100$",
        image: ProductThree,
    },
    {
        id: "01",
        title: "Product One",
        price: "30$",
        image: ProductOne,
    },
     {
        id: "02",
        title: "Product Two",
        price: "70$",
        image: ProductTwo,
    },
     {
        id: "03",
        title: "Product Three",
        price: "40$",
        image: ProductThree,
    },
    {
        id: "04",
        title: "Product Four",
        price: "50$",
        image: ProductOne,
    },
     {
        id: "05",
        title: "Product Five",
        price: "40$",
        image: ProductTwo,
    },
     {
        id: "06",
        title: "Product Six",
        price: "550$",
        image: ProductThree,
    },
     {
        id: "07",
        title: "Product Seven",
        price: "110$",
        image: ProductOne,
    },
     {
        id: "08",
        title: "Product Eight",
        price: "140$",
        image: ProductTwo,
    },
     {
        id: "09",
        title: "Product Nine",
        price: "100$",
        image: ProductThree,
    },
    {
        id: "01",
        title: "Product One",
        price: "30$",
        image: ProductOne,
    },
     {
        id: "02",
        title: "Product Two",
        price: "70$",
        image: ProductTwo,
    },
     {
        id: "03",
        title: "Product Three",
        price: "40$",
        image: ProductThree,
    },
    {
        id: "04",
        title: "Product Four",
        price: "50$",
        image: ProductOne,
    },
     {
        id: "05",
        title: "Product Five",
        price: "40$",
        image: ProductTwo,
    },
     {
        id: "06",
        title: "Product Six",
        price: "550$",
        image: ProductThree,
    },
     {
        id: "07",
        title: "Product Seven",
        price: "110$",
        image: ProductOne,
    },
     {
        id: "08",
        title: "Product Eight",
        price: "140$",
        image: ProductTwo,
    },
     {
        id: "09",
        title: "Product Nine",
        price: "100$",
        image: ProductThree,
    },
    {
        id: "01",
        title: "Product One",
        price: "30$",
        image: ProductOne,
    },
     {
        id: "02",
        title: "Product Two",
        price: "70$",
        image: ProductTwo,
    },
     {
        id: "03",
        title: "Product Three",
        price: "40$",
        image: ProductThree,
    },
    {
        id: "04",
        title: "Product Four",
        price: "50$",
        image: ProductOne,
    },
     {
        id: "05",
        title: "Product Five",
        price: "40$",
        image: ProductTwo,
    },
     {
        id: "06",
        title: "Product Six",
        price: "550$",
        image: ProductThree,
    },
     {
        id: "07",
        title: "Product Seven",
        price: "110$",
        image: ProductOne,
    },
     {
        id: "08",
        title: "Product Eight",
        price: "140$",
        image: ProductTwo,
    },
     {
        id: "09",
        title: "Product Nine",
        price: "100$",
        image: ProductThree,
    },
    {
        id: "01",
        title: "Product One",
        price: "30$",
        image: ProductOne,
    },
     {
        id: "02",
        title: "Product Two",
        price: "70$",
        image: ProductTwo,
    },
     {
        id: "03",
        title: "Product Three",
        price: "40$",
        image: ProductThree,
    },
    {
        id: "04",
        title: "Product Four",
        price: "50$",
        image: ProductOne,
    },
     {
        id: "05",
        title: "Product Five",
        price: "40$",
        image: ProductTwo,
    },
     {
        id: "06",
        title: "Product Six",
        price: "550$",
        image: ProductThree,
    },
     {
        id: "07",
        title: "Product Seven",
        price: "110$",
        image: ProductOne,
    },
     {
        id: "08",
        title: "Product Eight",
        price: "140$",
        image: ProductTwo,
    },
     {
        id: "09",
        title: "Product Nine",
        price: "100$",
        image: ProductThree,
    },
    {
        id: "01",
        title: "Product One",
        price: "30$",
        image: ProductOne,
    },
     {
        id: "02",
        title: "Product Two",
        price: "70$",
        image: ProductTwo,
    },
     {
        id: "03",
        title: "Product Three",
        price: "40$",
        image: ProductThree,
    },
    {
        id: "04",
        title: "Product Four",
        price: "50$",
        image: ProductOne,
    },
     {
        id: "05",
        title: "Product Five",
        price: "40$",
        image: ProductTwo,
    },
     {
        id: "06",
        title: "Product Six",
        price: "550$",
        image: ProductThree,
    },
     {
        id: "07",
        title: "Product Seven",
        price: "110$",
        image: ProductOne,
    },
     {
        id: "08",
        title: "Product Eight",
        price: "140$",
        image: ProductTwo,
    },
     {
        id: "09",
        title: "Product Nine",
        price: "100$",
        image: ProductThree,
    },
    {
        id: "01",
        title: "Product One",
        price: "30$",
        image: ProductOne,
    },
     {
        id: "02",
        title: "Product Two",
        price: "70$",
        image: ProductTwo,
    },
     {
        id: "03",
        title: "Product Three",
        price: "40$",
        image: ProductThree,
    },
    {
        id: "04",
        title: "Product Four",
        price: "50$",
        image: ProductOne,
    },
     {
        id: "05",
        title: "Product Five",
        price: "40$",
        image: ProductTwo,
    },
     {
        id: "06",
        title: "Product Six",
        price: "550$",
        image: ProductThree,
    },
     {
        id: "07",
        title: "Product Seven",
        price: "110$",
        image: ProductOne,
    },
     {
        id: "08",
        title: "Product Eight",
        price: "140$",
        image: ProductTwo,
    },
     {
        id: "09",
        title: "Product Nine",
        price: "100$",
        image: ProductThree,
    },
    {
        id: "01",
        title: "Product One",
        price: "30$",
        image: ProductOne,
    },
     {
        id: "02",
        title: "Product Two",
        price: "70$",
        image: ProductTwo,
    },
     {
        id: "03",
        title: "Product Three",
        price: "40$",
        image: ProductThree,
    },
    {
        id: "04",
        title: "Product Four",
        price: "50$",
        image: ProductOne,
    },
     {
        id: "05",
        title: "Product Five",
        price: "40$",
        image: ProductTwo,
    },
     {
        id: "06",
        title: "Product Six",
        price: "550$",
        image: ProductThree,
    },
     {
        id: "07",
        title: "Product Seven",
        price: "110$",
        image: ProductOne,
    },
     {
        id: "08",
        title: "Product Eight",
        price: "140$",
        image: ProductTwo,
    },
     {
        id: "09",
        title: "Product Nine",
        price: "100$",
        image: ProductThree,
    },
    {
        id: "01",
        title: "Product One",
        price: "30$",
        image: ProductOne,
    },
     {
        id: "02",
        title: "Product Two",
        price: "70$",
        image: ProductTwo,
    },
     {
        id: "03",
        title: "Product Three",
        price: "40$",
        image: ProductThree,
    },
    {
        id: "04",
        title: "Product Four",
        price: "50$",
        image: ProductOne,
    },
     {
        id: "05",
        title: "Product Five",
        price: "40$",
        image: ProductTwo,
    },
     {
        id: "06",
        title: "Product Six",
        price: "550$",
        image: ProductThree,
    },
     {
        id: "07",
        title: "Product Seven",
        price: "110$",
        image: ProductOne,
    },
     {
        id: "08",
        title: "Product Eight",
        price: "140$",
        image: ProductTwo,
    },
     {
        id: "09",
        title: "Product Nine",
        price: "100$",
        image: ProductThree,
    },
    {
        id: "01",
        title: "Product One",
        price: "30$",
        image: ProductOne,
    },
     {
        id: "02",
        title: "Product Two",
        price: "70$",
        image: ProductTwo,
    },
     {
        id: "03",
        title: "Product Three",
        price: "40$",
        image: ProductThree,
    },
    {
        id: "04",
        title: "Product Four",
        price: "50$",
        image: ProductOne,
    },
     {
        id: "05",
        title: "Product Five",
        price: "40$",
        image: ProductTwo,
    },
     {
        id: "06",
        title: "Product Six",
        price: "550$",
        image: ProductThree,
    },
     {
        id: "07",
        title: "Product Seven",
        price: "110$",
        image: ProductOne,
    },
     {
        id: "08",
        title: "Product Eight",
        price: "140$",
        image: ProductTwo,
    },
     {
        id: "09",
        title: "Product Nine",
        price: "100$",
        image: ProductThree,
    },
    {
        id: "01",
        title: "Product One",
        price: "30$",
        image: ProductOne,
    },
     {
        id: "02",
        title: "Product Two",
        price: "70$",
        image: ProductTwo,
    },
     {
        id: "03",
        title: "Product Three",
        price: "40$",
        image: ProductThree,
    },
    {
        id: "04",
        title: "Product Four",
        price: "50$",
        image: ProductOne,
    },
     {
        id: "05",
        title: "Product Five",
        price: "40$",
        image: ProductTwo,
    },
     {
        id: "06",
        title: "Product Six",
        price: "550$",
        image: ProductThree,
    },
     {
        id: "07",
        title: "Product Seven",
        price: "110$",
        image: ProductOne,
    },
     {
        id: "08",
        title: "Product Eight",
        price: "140$",
        image: ProductTwo,
    },
     {
        id: "09",
        title: "Product Nine",
        price: "100$",
        image: ProductThree,
    },
    {
        id: "01",
        title: "Product One",
        price: "30$",
        image: ProductOne,
    },
     {
        id: "02",
        title: "Product Two",
        price: "70$",
        image: ProductTwo,
    },
     {
        id: "03",
        title: "Product Three",
        price: "40$",
        image: ProductThree,
    },
    {
        id: "04",
        title: "Product Four",
        price: "50$",
        image: ProductOne,
    },
     {
        id: "05",
        title: "Product Five",
        price: "40$",
        image: ProductTwo,
    },
     {
        id: "06",
        title: "Product Six",
        price: "550$",
        image: ProductThree,
    },
     {
        id: "07",
        title: "Product Seven",
        price: "110$",
        image: ProductOne,
    },
     {
        id: "08",
        title: "Product Eight",
        price: "140$",
        image: ProductTwo,
    },
     {
        id: "09",
        title: "Product Nine",
        price: "100$",
        image: ProductThree,
    },
    {
        id: "01",
        title: "Product One",
        price: "30$",
        image: ProductOne,
    },
     {
        id: "02",
        title: "Product Two",
        price: "70$",
        image: ProductTwo,
    },
     {
        id: "03",
        title: "Product Three",
        price: "40$",
        image: ProductThree,
    },
    {
        id: "04",
        title: "Product Four",
        price: "50$",
        image: ProductOne,
    },
     {
        id: "05",
        title: "Product Five",
        price: "40$",
        image: ProductTwo,
    },
     {
        id: "06",
        title: "Product Six",
        price: "550$",
        image: ProductThree,
    },
     {
        id: "07",
        title: "Product Seven",
        price: "110$",
        image: ProductOne,
    },
     {
        id: "08",
        title: "Product Eight",
        price: "140$",
        image: ProductTwo,
    },
     {
        id: "09",
        title: "Product Nine",
        price: "100$",
        image: ProductThree,
    },
]

export default data